
spring:
  cloud:
    stream:
      function:
        definition: process;anotherProcess;send;increment;obj;
      bindings:
        send-out-0:
          destination: random-int
        process-in-0:
          destination: process
        anotherProcess-in-0:
          destination: process
        increment-in-0:
          destination: process
        increment-out-0:
          destination: increment-out
        obj-in-0:
          destination: obj-stream
