
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: sendtodlq
#          bindings.<processor-name>.consumer.dlqName: generic-dlq <== alternative to DlqDestinationResolver
      function:
        definition: process;anotherProcess;send;increment;obj;
      bindings:
        send-out-0:
          destination: random-int
        process-in-0:
          destination: process
        anotherProcess-in-0:
          destination: process
        increment-in-0:
          destination: process
        increment-out-0:
          destination: increment-out
        obj-in-0:
          destination: obj-stream
